### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by DreadedLama** [AndroPlus-org/magisk-module-camerasound#2]
Does the module still work? I'm trying it but it doesn't seem to work.
My device is Pixel 7 with the latest Android 13 Beta build

**Comment by AndroPlus-org** [comment]
I don't have a Pixel 7 anymore, so I can't confirm & test...

**Comment by dreadedlama** [comment]
Ok, thanks for the quick reply

**Comment by sun-jiao** [comment]
I am using it on Pixel 8 (Japanese version) with android 14, it works fine. I guess it may conflict with your other modules.

Thank you @AndroPlus-org for this good work. I think this information can be added in the newest release message. Otherwise someone might think it is not compatible with Android 14.

**Comment by dreadedlama** [comment]
> I am using it on Pixel 8 (Japanese version) with android 14, it works fine. I guess it may conflict with your other modules.

I tried again and it still isn't working for me. Can you tell me the modules that you are using? Also, did you follow any specific procedure or just simply flashed the module? I might be doing something wrong here

EDIT: I just using the bare minimum modules - Shamiko, Systemlesshost, USF , Zygisk and  Google Photos unlimited backup. That's it

**Comment by sun-jiao** [comment]
@DreadedLama I installed the module in Magisk app and rebooted my phone, that's all. My other modules include Google Photos unlimited backup, Enhanced Storage Isolation, LSPosed and a font module for Chinese characters. 

Could you provide a files list of the /system/product/media/audio/ui directory?

**Comment by dreadedlama** [comment]
@sun-jiao  I followed the same steps. I see the camera_click.ogg is replaced with the empty audio file in the module but still, when I click a picture from my camera, I hear the clicking sound

**Comment by sun-jiao** [comment]
@ DreadedLama Oh. I don't know what the problem is.

**Comment by dreadedlama** [comment]
@sun-jiao  I guess I'll look into this again when I get some time. Thanks for letting me know it works.
